// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJb_vfJwfKlJJfl3Q3QQLOQ6e7JLGRn8w',
    appId: '1:302024968063:web:4dba822d78069e065fbc4a',
    messagingSenderId: '302024968063',
    projectId: 'lashess-by-prii',
    authDomain: 'lashess-by-prii.firebaseapp.com',
    storageBucket: 'lashess-by-prii.firebasestorage.app',
    measurementId: 'G-B6GB71YN0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvdPZYogVCNYDui4nmhs1NF3EFYke1fT0',
    appId: '1:302024968063:android:995c95b92549bc355fbc4a',
    messagingSenderId: '302024968063',
    projectId: 'lashess-by-prii',
    storageBucket: 'lashess-by-prii.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxUjqpmsklJS97LB1kDzcm6CXAHRlN1TY',
    appId: '1:302024968063:ios:135650935e7d92c95fbc4a',
    messagingSenderId: '302024968063',
    projectId: 'lashess-by-prii',
    storageBucket: 'lashess-by-prii.firebasestorage.app',
    androidClientId: '302024968063-6fmm1ffar50vn22gqk3th70340n3ikm7.apps.googleusercontent.com',
    iosClientId: '302024968063-4lggpal1pmrhmp7batohcggm81ttmf82.apps.googleusercontent.com',
    iosBundleId: 'com.example.lashessByPriiApp',
  );

}